apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virusdefinition-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clamav
  labels:
    k8s-app: clamav-host-scanner
spec:
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - name: clamav-scanner
        image: mkodockx/docker-clamav:alpine
        ports:
          - containerPort: 3310
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
	  requests:
            cpu: "1"
            memory: 2Gi
	
	volumeMounts:
          - name: host-fs
	    mountPath: /host-fs
            
          - name: virus-definition
            mountPath: /var/lib/clamav
	   
          - name: logs
            mountPath: /var/log/clamav
          
        livenessProbe:
          periodSeconds: 10
          exec:
            command: ["/check.sh"]
        readinessProbe:
          initialDelaySeconds: 60
          exec:
            command: ["/check.sh"]
        volumes:
        - name: host-fs
          hostPath:
            path: /
            
        - name: logs
          emptyDir: {}
        
        - name: virus-definition
          hostPath: 
            path: /tmp/clamav
---
apiVersion: v1
kind: ConfigMap
metadata:
        name: clamav
        data:
            clamd.conf: |
              Foreground yes
              Debug no
              LeaveTemporaryFiles no
              LogFile /dev/stdout
              LogFileMaxSize 0
              LogTime yes
              LogClean no
              TCPSocket 3310
              TCPAddr 0.0.0.0
              ExcludePath ^/proc/
              ExcludePath ^/sys/
              ExcludePath ^/host/proc/
              ExcludePath ^/host/sys/
              MaxDirectoryRecursion 64
              FollowDirectorySymlinks no
              FollowFileSymlinks no
               
              CrossFilesystems no
              FollowFileSymlinks no
            freshclam.conf: |
              Foreground yes
              DatabaseDirectory /var/lib/clamav
              UpdateLogFile /dev/stdout
              Debug no
              LogFileMaxSize 0
              LogTime yes
              DatabaseOwner root
              DNSDatabaseInfo current.cvd.clamav.net
              DatabaseMirror database.clamav.net
              MaxAttempts 3
              ScriptedUpdates yes
              CompressLocalDatabase no
              TestDatabases yes
              SafeBrowsing no
              Bytecode no
              Checks 12
              NotifyClamd /etc/clamav/clamd.conf
              ConnectTimeout 30
              ReceiveTimeout 60
